# https://docs.docker.com/compose/compose-file/
# https://docs.docker.com/compose/production/

version: '2'

services:
  accounts_core:
    image: registry.pmjlle.joinville.sc.gov.br:5000/pmj/accounts-core:${CI_BUILD_REF}
    restart: "always"
    ports:
      - "10003:80"
    environment:
      - STORAGE_CONNECTION_STRING
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - ASPNETCORE_ENVIRONMENT=Production
	  - Token
	  - UrlSei
	  - SeiEncoding
	  - VirtualUrl
	  - Anexo
	  - Unidade
	  - Formulario
	  - Procedimento
	  - TipoProcedimento
	  - Servico
	  - MailServer
	  - MailPort
	  - MailUser
	  - MailPassword